### ISSUE TITLE
Would you mind adding a license?

### ISSUE THREAD

**Issue by csajedi** [Kevoot/MultiTapeTuringMachine#1]
Hello, 

I am writing a Turing machine simulator for assemblyscript as a hobby project and your TM is quite well made. I'd love to use it as the basis but it doesn't presently have a license. Could you add a license so I can understand what kind of reuse is acceptable? If I could be so bold as to request one, it'd be MIT :)

**Comment by Kevoot** [comment]
Added an MIT license as requested
